### ISSUE TITLE
TaurusWheel not updated

### ISSUE THREAD

**Issue by hayg25** [taurus-org/taurus#1031]
Dear all,
I did small test using tauruswheel and realized that the value is not updated if I change it using another program like atkpanel for example.
We could see a blue box around the value showing that the displayed value is different from the one in Tango but no update ...
The only way to update is to restart the program....
Is there a method in the class I could call to update the value ?

Thx

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hayg25** [comment]
Dear all, 
Ok from what I understand the TaurusheelEdit is write only, so I understand why I does not update.

**Comment by cpascual** [comment]
Yes, as you already noticed, TaurusWheelEdit is a "write widget", and *by design* the taurus write widgets do not change their displayed value when the value changes. This is on purpose, because it would be very annoying if the interface kept changing *while you were trying to use it to modify the value*.

The solution is of course to use 2 widgets: one for viewing the (read or write) value and another to edit the write value.

If you need something compact, consider using a [TaurusReadWriteSwitcher](http://taurus-scada.org/devel/api/taurus/qt/qtgui/compact/_TaurusReadWriteSwitcher.html) (which BTW, is what TaurusForm uses when you set it in ["compact mode"](http://taurus-scada.org/users/ui/forms.html#compact-mode))
