### ISSUE TITLE
Button to swicth boolean attribute state 

### ISSUE THREAD

**Issue by hayg25** [taurus-org/taurus#1124]
Dear All, 
I would like to create a button to modify an attribute state (Boolean). 
I tried TaurusCommandButton using a command ( = a function I implemented that modifies the Boolean value using PyTango). 

What's the correct way ? 

Thx

**Comment by cpascual** [comment]
We normally use [TaurusValueCheckbox](http://taurus-scada.org/devel/api/taurus/qt/qtgui/input/_TaurusValueCheckBox.html) for this, because it is more evident which is the current setting.

If you specifically want a button, it can be created quite easily inheritting from QPushButton and TaurusBaseWidget (or maybe TaurusBaseWritableWidget)... if you want help with that, I could give a quick snippet (but I personally would prefer the TaurusValueCheckbox)

**Comment by hayg25** [comment]
Dear @cpascual , 
thx for your answer, ok I use TaurusValueCheckbox then. 

Cheers
