### ISSUE TITLE
taurus designer not loading taurus extensions

### ISSUE THREAD

**Issue by evaki1** [taurus-org/taurus#1166]
Hello,

I am on Windows 10 and have installed the following using pip:
Tango: 9.3.3
PyTango: 9.3.1
Python: 3.6.8
Taurus: 4.7.0
PyQt5: 5.15.1

and when I launch taurus designer the Qt designer doesn't show the taurus extensions.
Any ideas on what is causing this?

Thanks,
Eva

**Comment by cpascual** [comment]
Hi @evaki1 ,
This worked [when I tested  the 4.7.0 release on windows10](https://github.com/taurus-org/taurus/issues/1134#issuecomment-668599362). So my first suspect would be about some difference in one of the dependencies (pyqt?) since you install everything with pip whereas [I used a conda environment](https://github.com/taurus-org/taurus/issues/1134#issue-672205916) for the dependencies.

So, could you try checking if by installing with (ana)conda fixes it for you?

For this you need to install either anaconda or miniconda (I used [miniconda](https://docs.conda.io/en/latest/miniconda.html)) and run the following **in the "anaconda prompt"**:

```console
conda config --add channels conda-forge
conda config --add channels tango-controls
conda create -n taurus python=3 pyqt=5 pytango lxml future guidata guiqwt ipython pillow pint ply pyqtgraph pythonqwt numpy scipy pymca click
conda activate taurus
pip install taurus
pip install taurus_pyqtgraph
```
then just run `taurus designer` in the same prompt

**Comment by evaki1** [comment]
Hi @cpascual 

Sorry for the delayed answer but this worked perfectly!
Thank you very much!
