### ISSUE TITLE
Tango synoptic viewer laggy

### ISSUE THREAD

**Issue by mariocaptain** [taurus-org/taurus#1176]
Hi all,

I am sorry if this question is not directly related to Taurus.
In my project I need to display a synoptic of about 100 devices with about 200 attributes.

I love Taurus, but the reason I don't opt to use **TaurusJDrawSynopticsView** is because:
- It does not support Dynamic Objects which are needed in my application (e.g. I need to change color of lines, shapes etc as attribute values change)
- It doesn't display the bar widget correctly
- The general aesthetics is not as good as that of the built-in tango synoptic viewer at this stage

So I have been using the tango's java built-in synoptic viewer (**fr.esrf.tangoatk.widget.jdraw.SimpleSynopticAppli**), so far so good.

The problem is that I am running the viewer together with several Taurus Gui applications, all on a Raspberry Pi 4, and while the Taurus Gui programs are very smooth in updating the attribute values (usually < 1 second), the **SimpleSynopticAppli** is very laggy in updating changes of attribute (usually from 3 to 10 seconds).

For most of the attributes, I set a change event in the `device_init()` function of the device server, and push changes in their `read `and `write `functions.

In the Diagnostics menu of the synoptic viewer, I can see that the viewer seems to do both polling and event listening, and the update period is set at the default 1000 milliseconds (can't be lowered). 

Does anyone experience the same?

**Comment by cpascual** [comment]
Hi

I cannot comment on the java application. WeI don't use it.

But regarding taurus jdraw viewer,  note that some of its elements are dynamic (e.g. , attribute values can be displayed, and backgroud colors are updated) . With this I mean that it should be possible to implement other required dynamism with taurus jdraw viewer.

Finally, you may be interested in https://github.com/MaxIV-KitsControls/lib-maxiv-svgsynoptic , which is a very interesting synoptic viewer compatible with taurus and based on SVG instead of jdraw files.

**Comment by mariocaptain** [comment]
Thanks so much @cpascual !
