### ISSUE TITLE
taurusgui --new-gui doesn't generate config

### ISSUE THREAD

**Issue by daneos** [taurus-org/taurus#355]
Generated config.xml file is empty and gui can't be launched.
Log: [taurusgui_new_gui.txt](https://github.com/taurus-org/taurus/files/642425/taurusgui_new_gui.txt)

Test system:
Centos 7 x86-64
Python 2.7.5
Tango 9.2
Taurus 4.0.1

**Comment by cpascual** [comment]
Hi, sorry for replying so late... It seems that your issue slipped unnoticed by all (including me).

From the log file, I see a couple of exceptions that could be related with your error.
~~~
 Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/taurus/qt/qtgui/taurusgui/appsettingswizard.py", line
79, in valueChanged
self.valueChanged.emit(self._actualValue, not self._actualValue)
AttributeError: 'function' object has no attribute 'emit'
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/taurus/qt/qtgui/taurusgui/appsettingswizard.py", line
1288, in initializePage
xml, substitutions = self.wizard().generateXml()
File "/usr/lib/python2.7/site-packages/taurus/qt/qtgui/taurusgui/appsettingswizard.py", line
1597, in generateXml
if SARDANA_INSTALLED and self.__getitem__("macroServerName"):
NameError: global name 'SARDANA_INSTALLED' is not defined
MainThread INFO 2016-12-06 13:45:14,976 TaurusRootLogger: 

~~~

But I've just run `taurusgui --new-gui` and created a config.xml without problems, so could you test with the latest release (4.0.3) and, if the problem is still there, provide us with step-by-step instructions to reproduce it?

**Comment by daneos** [comment]
Hi,
It seems that in 4.0.3 the problem does not appear anymore.
Thanks.
