### ISSUE TITLE
Attribute range and quantities

### ISSUE THREAD

**Issue by reszelaz** [taurus-org/taurus#386]
I have a doubt if the bellow behavior is correct:
`mot01/position` Tango attribute has unit set to `mrad`.

I set the range:
~~~
import taurus
a = taurus.Attribute("mot01/position")
a.setRange(-10,10)
~~~

and it sets in the database Tango range of -10000 and 10000.

**Comment by teresanunez** [comment]
Hi Zibi,
            are you sure that the -10000 and 10000 that you see are not the default values that
 usually Tango put?, I have tried it and the range is not changed at all with setRange, for me
 it stays always set at (-10000,10000) independently of what I put as argument.

                                 Regards,
                                                    Teresa

**Comment by reszelaz** [comment]
Yes, in my case it indeed saves the new value in the database. If I set range to -1 and 1 it sets -1000 and 1000 in the database.

**Comment by cpascual** [comment]
I confirm what zibi says.

And I think I understand why it happens. The problem is related to the fact that "radians" is actually an *adimensional* quantity. 

When you call setRange, you should use quantities (see entries 20 and 22 of the examples below, where I get errors if I try to set something without dimensions). 

If you use quantities as I do in entry 15, it works as expected.

Now the case with the mrad is that in the database, thing are stored as **milli**radians (which is to say "milli-adimensional"). And when you pass just a number (which is "adimensional"), it gets encoded to "milli-adimensional" by multiplying by 1000.

This is confusing, but it only occurs for adimensional "pseudoquantities" like mrad, since for other things the dimensionality check prevents to use setRange without units. And I do not know if there is anythong we can do to prevent it since in some sense "it makes sense for pint")


Examples:

In the following example, mot01/position units are not set (dimensionless), mot02/position units are set to 'mrad' and mot03/position units are set to 'ampere'.

```
Door_kk_1 [3]: a=taurus.Attribute("mot01/position")

Door_kk_1 [6]: a.range

        Result [6]: [<Quantity(-inf, 'dimensionless')>, <Quantity(inf, 'dimensionless')>]

Door_kk_1 [7]: a.setRange(-2,2)

Door_kk_1 [8]: a.read().range
        Result [8]: [<Quantity(-2.0, 'dimensionless')>, <Quantity(2.0, 'dimensionless')>]

Door_kk_1 [10]: b=taurus.Attribute("mot02/position")

Door_kk_1 [11]: b.rvalue
        Result [11]: <Quantity(0.0, 'milliradian')>

Door_kk_1 [12]: b.setRange(-3,3)

Door_kk_1 [14]: b.range
        Result [14]: [<Quantity(-3000.0, 'milliradian')>, <Quantity(3000.0, 'milliradian')>]

Door_kk_1 [15]: b.setRange('-2 mrad', '2 mrad')

Door_kk_1 [16]: b.range
        Result [16]: [<Quantity(-2.0, 'milliradian')>, <Quantity(2.0, 'milliradian')>]

Door_kk_1 [17]: c=taurus.Attribute("mot03/position")

Door_kk_1 [18]: c.rvalue
        Result [18]: <Quantity(0.0, 'ampere')>

Door_kk_1 [19]: c.range
        Result [19]: [<Quantity(-inf, 'ampere')>, <Quantity(inf, 'ampere')>]

Door_kk_1 [20]: c.setRange(4,4)
AssertionError: low and rvalue have different dimensionality
(For more detailed information type: python_error)

Door_kk_1 [22]: c.setRange('-4 A','4 A')

Door_kk_1 [25]: c.range
        Result [25]: [<Quantity(-4.0, 'ampere')>, <Quantity(4.0, 'ampere')>]
```

**Comment by teresanunez** [comment]
Sorry, for the question, but should also work like this in taurus3?. I don't get it at all.

**Comment by reszelaz** [comment]
No, the Quantities were introduced with TEP14, so it it Taurus 4 only.

**Comment by teresanunez** [comment]
I answer my self, no, it should not. I get it now with taurus4

**Comment by cpascual** [comment]
Another way to understand this problem is understanding that [units are not the same as dimensions](http://physics.stackexchange.com/a/193699) (something may have units and be adimensional). It also helps to see how pint treats adimensional quantities:

```
from taurus.external.pint import Q_
a = Q_('1 mrad')
print a
<Quantity(1, 'milliradian')>
print a.to_root_units()
<Quantity(0.001, 'radian')>
print a+2
<Quantity(2.001, 'dimensionless')>
```

**Comment by cpascual** [comment]
I did some quick research to see if there is a way to tell pint *not* to accept `2` as equivalent to `2 rad`, but I didn't find it. If someone knows a way please say so.

But for now, I think that the issue can be closed **with the recommendation of always expliciting units**  when working with quantities.
