### ISSUE TITLE
check_dependencies could be removed

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#406]
Since the move of taurus to use setuptools, the check_dependencies mechanism (implemented in taurushelper.py) is kind of redundant and maintaining it is burdensome (dependencies need to be updated twice) . IMHO dependencies should be taken care of by the distribution method (setuptools, or linux distro, or whatever), so I propose to deprecate and remove check_dependencies() and related stuff

**Comment by bilderbuchi** [comment]
I took a quick look at the code, and it could probably be slimmed down:
* E.g. by using [setuptools.version.pkg_resources.parse_version()](https://packaging.pypa.io/en/latest/version/#packaging.version.parse) instead of doing both __get_python_version_number() and __get_python_version() for comparing versions.
* Much of the functions for checking the different packages seems to basically repeat themselves - that could probably be refactored into one checker function, making maintenance much easier.

But yeah, if setuptools/pip/whatever can ensure the dependencies are there, that should also work. You can probably use [extras_require](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) to manage the optional/component-specific dependencies.

**Comment by cpascual** [comment]
Regarding all the optional/component specific dependencies: my intention is to deal with them as part of the [future plugin system](http://www.taurus-scada.org/tep/?TEP13.md)
