### ISSUE TITLE
how to use get_property method on taurus device / attribute proxy 

### ISSUE THREAD

**Issue by tcsgmrt** [taurus-org/taurus#447]
Dear All,

I have created taurus Attribute proxy for my device server attribute and I want to use get_property method on that proxy but it's raise attribute error. As per my knowledge taurus device and attribute proxy are inherited from PyTango Device and Attribute Proxy so  get_property should work for taurus attribute proxy.
I have used taurus attribute proxy as below:
        AttrProxy = taurus.Attribute(attributeModel)
        AttrProxy.get_property('PropertyName')

It's show error as below:
File "taurus/core/tango/tangoattribute.py", line 77, in __getattr__
    return getattr(self._getRealConfig(), name)
  File "taurus/core/tango/tangoconfiguration.py", line 75, in __getattr__
    raise AttributeError
AttributeError

**Comment by cpascual** [comment]
Hi @tcsgmrt 

> As per my knowledge taurus device and attribute proxy are inherited from PyTango Device and Attribute Proxy so get_property should work for taurus attribute proxy.

Not strictly right.

(Note: all the explanation below is based on Taurus4 API which differs in this aspect from Taurus3. But while the names of the classes may not match, the explanation is, in essence valid also for Taurus3)

Neither taurus.Device inherits from PyTango.DeviceProxy nor taurus.Attribute inherits from PyTango.Attribute.

Instead, when you do `taurus.Device("tango:a/b/c/d")`, you get a "Taurus Device" which in this case happens to be of the class  `taurus.core.tango.TangoDevice`. This class does not inherit from `PyTango.DeviceProxy` but it behaves almost as if it did, because it keeps an internal reference to a `PyTango.DeviceProxy` and implements its `__get_attr__()` method to expose the API of the `PyTango.DeviceProxy` transparently.

In contrast, the case of the Taurus.Attribute is different. In this case, Taurus does not use the `PyTango.AttributeProxy` at all.  When you do `Taurus.Attribute("tango:a/b/c/d")` you get a "Taurus Attribute" that in this case happens to be a `taurus.core.tango.TangoAttribute`.
This class does not hold any reference to a `PyTango.AttributeProxy` and does not expose such API (it does expose the API of a `PyTango.AttributeInfoEx` object instead).

So now, the question is how to access a tango attribute property. And the answer is that, right now, Taurus is not providing any special mechanisms for that (keep in mind that Taurus != tango). 
So, *right now* you would need to use PyTango for that access (no problem in importing both taurus and PyTango in the same script, there won't be a performance penalty since Taurus already imports PyTango when you are accessing tango).

**But** I think that, just as  `taurus.core.tango.TangoDevice` provides `getDeviceProxy` to access the PyTango device proxy, It would be trivial to add a `getAttributeProxy()` method to  `taurus.core.tango.TangoAttribute` . If you think that this may be useful, just say so and we can add it soon.

Cheers,

Carlos

**Comment by tcsgmrt** [comment]
Dear Carlos,

Thanks for your reply. It will really help me if adding of  getAttributeProxy method to taurus.core.tango.TangoAttribute  would provide get_property method to taurus.Attribute proxy.

Hope to here from you.

Thanks,
Hitesh Patel
Tcs,Pune

**Comment by cpascual** [comment]
I just created the following PR: #450 

With it, you can do:

```python
attr = taurus.Attribute(attributeModel)
attr_proxy = attr.getAttributeProxy()
prop = attr_proxy.get_property('PropertyName')
```
Please, try it and confirm if it works for you

**Comment by cpascual** [comment]
Closing this as solved (#450 has already been merged into develop)

**Comment by tcsgmrt** [comment]
Dear Carlos,

As per your suggestion I have created taurus attribute proxy and tried to used get_property method but it didn't work for me.
Below is the log for that:
**>>> import taurus
>>> attr = taurus.Attribute('01hw255506:10000/machine01/position')
>>> attr_proxy = attr.getAttributeProxy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/tangoworkspace/CentralNode/GUI/cmcGuiLib/cmcGUI/taurus/core/tango/tangoattribute.py", line 77, in __getattr__
    return getattr(self._getRealConfig(), name)
  File "/opt/tangoworkspace/CentralNode/GUI/cmcGuiLib/cmcGUI/taurus/core/tango/tangoconfiguration.py", line 75, in __getattr__
    raise AttributeError
AttributeError**

My system taurus and tango version details are as follow:
taurus : 3.7.0
tango : 8.1.8

**Comment by cpascual** [comment]
> taurus : 3.7.0

In order to try this new feature, you need to install taurus from the develop branch
(and note that since you are currently using the old taurus 3, some of your code may need to be adapted to work on taurus 4)
