### ISSUE TITLE
init_bkcomp is missing

### ISSUE THREAD

**Issue by rile993** [taurus-org/taurus#451]
Hi guys,

I had installed PyQt (Qt version: 4.8.7, SIP version: 4.19.2, PyQ versiont: 4.12).
Then, I wanted to install taurusdesigner with script which is showed below:

`#!/bin/bash`
`sudo apt-get install python3-guiqwt python3-spyderlib`
`sudo -H pip3 install  h5py lxml PLY`
`sudo -H pip3 install taurus`

But, when i wanted to start it from the terminal, this is what I get:

`rile@Dell:~$ taurusdesigner`
`Traceback (most recent call last):`
`  File "/usr/local/bin/taurusdesigner", line 7, in <module>`
`    from taurus.qt.qtdesigner.taurusdesigner import main`
`  File "/usr/local/lib/python3.5/dist-packages/taurus/__init__.py", line 29, in <module>`
`    from .core import release as __R`
`  File "/usr/local/lib/python3.5/dist-packages/taurus/core/__init__.py", line 38, in <module>`
`    from init_bkcomp import *`
`ImportError: No module named 'init_bkcomp'`

Any ideas what is the problem, and how I can solve it?

Cheers

**Comment by cpascual** [comment]
Note that taurus does *not* yet support python3, so the first thing to change is installing the python 2 versions of the dependencies and using pip instead of pip3.

Furthermore, since you are using apt-get (I assume that you are on a Debian or Debian-based machine), so please note that taurus is available as a debian package and that you can cleanly install it with just `apt-get install python-taurus`

If what you want is to install a newer version of Taurus for which you do not have a .deb package, my recommendation is to first install all dependencies of taurus from the repositories and then install 
and then install taurus rfom whatever other source. Note that you can list the dependencies of taurus in debian with `apt-cache depends python-taurus`

Hope this helps

**Comment by rile993** [comment]
Hi, thank you for the response.

But I have installed PyQt for Python 3.5. Does this mean that If I want to use taurus, I need to install PyQt for Python 2.7?
Also, is there a plan to upgrade taurus in near future so it will support python 3.5?

Best regards

**Comment by cmft** [comment]
Hi @rile993 ,

> Does this mean that If I want to use taurus, I need to install PyQt for Python 2.7?

I'm afraid that yes.  We adapted taurus (V4) to accept PyQt new style signals, but Taurus.qt is implemented with python 2.7 rules. If you have been installed  the dependencies with ` apt-cache depends python-taurus` it should has installed.

> Also, is there a plan to upgrade taurus in near future so it will support python 3.5?

Yes, it is, but not in a short period. We had an opened issue #218 since a long time, but unfortunately we don't find a time slot. Fell free to create a new [TEP](https://github.com/taurus-org/taurus/blob/develop/doc/source/tep/index.md) for that.

**Comment by rile993** [comment]
Ok, that would be all then.
Thank you for your help guys. :)
