### ISSUE TITLE
Order of imports affects TaurusValueLineEdit

### ISSUE THREAD

**Issue by daneos** [taurus-org/taurus#457]
Hi,
During my investigation of faulty TaurusValueLineEdits , I found out that order in which TaurusApplication is imported along with other pieces of code affects correct operation of TaurusValueLineEdit.

Basically, if you import TA before any other GUI stuff, everything works as expected, but if you import it after your GUI, TVLE value is always orange and cannot be applied to the device.
I have noticed this behaviour with both Taurus 4.0.1 and 4.0.3.
I'm attaching example code that demonstrates the problem.
[tvle_test_app.zip](https://github.com/taurus-org/taurus/files/1025764/tvle_test_app.zip)

Tested on:
Centos 7, Tango 9.2.2, Taurus 4.0.1
Linux Mint 17.3, Tango 9.2.2, Taurus 4.0.3

**Comment by cmft** [comment]
Hi @daneos ,
The problem is due to the `PyQt4 import`  see  issue #411. 
If  you import PyQT4 before any Taurus.qt module the sip api is set to 1 (by default) and taurus (qt) requires api2.

The  solution to prevent this error is import qt modules from taurus. 
e.g 
 `from taurus.external.qt import QtGui`

**Comment by daneos** [comment]
Hi, indeed, when importing Qt from Taurus everything works, thank you!
