### ISSUE TITLE
How to read cuurent value of attribute using TaurusLabel not cached 

### ISSUE THREAD

**Issue by tcsgmrt** [taurus-org/taurus#461]
Dear All,

While displaying value using TaurusLabel if remote server is disconnected then it's showing cache value for certain period of time then replace with '----' if not available.

I want to set this **cache= False**  globally   for my application similar to how we set **changeDefaultPollingPeriod** for all taurus device used in application.

Please provide example if possible.

Thanks,
Hitesh Patel

**Comment by cpascual** [comment]
There is no way of setting cache=False globally for all reads. This is something you should d programmatically when you use the read method. Setting cache=False globally would almost certainly not have the effect you are looking for, and even if it did, it would be terrible in terms of efficiency.

Now... I may be wrong, but it looks that you are trying to set cache=False as part of an approach that may not be ideal... Maybe you should consider programming your system to use events instead of  relying on polling. 

Taurus uses its own client-side polling **only** when the Tango system does not provide events for the given attribute. The Tango system may provide events by directly pushing them in the Device Server (recommended way to go) or by configuring the Polling **in the Tango Database** for the given attribute. 

You should consider those options since they probably will help you in having a more responsive and efficient system.
