### ISSUE TITLE
[Travis] aborted builds (10m without output)

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#497]
We are lately seeing many spurious failures in travis where a test gets stuck (maybe an event lost?).
These are gone when retrying.

I open this issue to keep a record of these (the history is lost when restarting the build).
I propose to log them here in comments in order to find patterns.

**Comment by cpascual** [comment]
See: https://travis-ci.org/taurus-org/taurus/builds

At least the following builds have failed (although they may now be ok due to manually triggered rebuids):
270.2 , 273.2 276.2, 282.2, 284.2

Note that it is always the test on the debian9 docker (the ".2")

The test in which it fails varies, but it seems to be in taurus.core.tango.test.test_tangoattribute.AttributeTestCase  (although this may just be a coincidence due to timing)

A typical log in case of error ends as:
```
test_write_read_conf (taurus.core.tango.test.test_tangoattribute.AttributeTestCase)

Testing write_read_conf(expected=[<Quantity(100, 'dimensionless')>, <Quantity(300, 'dimensionless')>], cfg='alarms', attr_name='short_scalar_nu', value=[100, 300]) ... 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by cpascual** [comment]
I wonder if it may be that Travis only considers "stdout" for output and maybe the test suite is using stderr... (or something like this). To check it we could try to redirect the output when calling testsuite...

**Comment by reszelaz** [comment]
I have observed something very similar with the sardanatestsuite. At some point, after numerous subscription & unsubscription to the tango attributes, the events stops arriving to the tests. This is 100% reproducible with the sardanatestsuite on Debian9 with the standard distribution packages. I have investigated it a little bit. For example, the events are correctly emitted by the server - another client running in parallel to the tests receives them. But finally I had to stop the investigation due to the lack of time....

In sardana we don't suffer it yet at Travis cause the sardanatestsuite docker image is still based on the Debian8.

**Comment by cpascual** [comment]
It seems to me that, after a period when this happened a lot, it is not happening anymore (or at least it happens much less often).

Maybe it is related with the changes in Travis infrastructure related to #601 ...

I suggest working a few more weeks and report here any cases of "spurious" Travis failures, and if we confirm the impression that they are gone, we can close this issue (for the moment)

**Comment by cpascual** [comment]
This is not hapenning anymore. We can confirm that the workaround worked. Closing
