### ISSUE TITLE
taurusplot : removing raw data from input data selection

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#501]
After adding raw data into Plot configuration dialog/input data selection, is it possible to simply remove one raw data and its curve?

I succeeded into removing the curve by setting Line/Style to "No line" but the legend still remains.

When I remove the "<label>" from the "Curve Title(s)..." button into the Plot configuration dialog, an empty place still remains when the erased raw data is not the last one.

**Comment by cpascual** [comment]
I am afraid there is no way (from the GUI)  to remove a RawData curve. To be honest, I think you are the first person in years using the Raw Data tab ;)  (some people add raw data curves, but they do it programmatically and remove them the same way).

So I agree that this is a missing feature, but (similar to what I said in https://github.com/taurus-org/taurus/issues/500#issuecomment-315039389) I think this is a minor problem which will be obsoleted by #TEP17 .

Note: as a workaround, you can use [eval attributes](http://www.taurus-scada.org/en/latest/devel/api/taurus/core/evaluation.html). For example, for plotting the xquare root of x where x goes from 0 to 4 in 100 steps, you could do:
```
$ taurusplot 'eval:linspace(0,4,100)|eval:sqrt(linspace(0,4,100))'
```
Using eval attributes is way more powerful than the raw data curves, since you can also include other attributes in your calculations, e.g.:
```
$ taurusplot 'eval:abs({tango:sys/tg_test/1/wave})'
```

In order to add models from the GUI instead of from the launcher, you can:
- open the Input Data selection Dialog 
- right click on the model list (the bottom area) --> Select Add new"Add new row" 
- double click on the newly-created model slot (marked as "Empty") and type the model.

See the following snapshot:

**Comment by PhilLAL** [comment]
I just made some tests but we actually but we just have one use case : adding lines for warning and error steps.
Actually, I suppose there are some filling stuff to add since nothing appears when I launch 
> $ taurusplot 'eval:linspace(0,4,100)|eval:sqrt(linspace(0,4,100))'

or 

> $ taurusplot 'eval:abs({tango:sys/tg_test/1/wave})'
Am I correct?

Note: a "!" appears when editing input data selection dialog and when double-clicking appears the eval line.
![input data selection dialog](https://framapic.org/FLimM3aGUAhI/1O4o2v59KjTI.png)

**Comment by cpascual** [comment]
>nothing appears when I launch
>       $ taurusplot 'eval:linspace(0,4,100)|eval:sqrt(linspace(0,4,100))'

Which version of taurus are you using?
My examples were valid for Taurus4.
For Taurus3 you should use `eval://` instead of  `eval:`
For example, the following should work in Taurus 3:

```
taurusplot 'eval://rand(100)'
```

> we just have one use case : adding lines for warning and error steps.
 But would you add them on the GUI? ... or would you do it programmatically?
If it is the later, you can use raw data and add/remove programmatically.

In any case, for a new development I suggest having a look at what we are preparing in TEP17 ( #452 ) (which is based oin pyqtgraph and is IMHO much simpler)

Also, just out of curiosity, what is it that you are considering taurus for?

**Comment by PhilLAL** [comment]
I ran my tests using tangobox. 
The goal is to discover how to use it and possibly use it for ThomX TANGO projet.
