### ISSUE TITLE
--config option for taurusform and taurusplot does not keep window size

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#502]
Hi again,
it seems --config option does not save window size so I need to resize window at every launch. 
I suspect this is the behaviour of all similar taurus command line options.

Is it a normal behaviour? In this case, what is the correct method to save window size?

**Comment by cpascual** [comment]
A similar issue was already reported (and fixed) for `taurusform` (see #114 ). There we [mentioned the possibility of doing the same  for `taurusplot` and `taurusform`](https://github.com/taurus-org/taurus/issues/114#issuecomment-260360383), but was not done. But, again, I think this can be implemented  as part of #452 for the coming pyqtgraph plots instead of for the old PyQwt5 ones .

**Comment by cpascual** [comment]
Actually I just implemented it (it was easy). See #508
