### ISSUE TITLE
[doc] html doc automatically load a github page

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#524]
Hello,
trying to read html doc offline, I downloaded taurus-latest.zip.
Opening the default index.html, I noticed that when I load taurus-latest/index.html#document-users/ui/index link (User's GUI), it loads https://github.com/taurus-org/taurus/blob/develop/doc/source/tep/index.md
Any idea why?

**Comment by cpascual** [comment]
I confirm it. It is a bug.
I guess it is related to a combination of 2 things:
- The html for offline reading prepared by Readthedocs merges **all** the doc pages into a single html
- The [TEP index](http://taurus-scada.org/en/latest/tep/index.html) page (which is included in the TOC of the docs) is an empty frontend that redirects to the github TEP index

When merging all the pages, the redirection must also be merged... In fact, if you load the index file and hit "ESC" before the redirection can be done, you will see the offline docs well.

In order to fix it, maybe we could avoid creating the automatic redirection and just show an external link that the user has to click in order to get there.

Thanks for reporting!

**Comment by cpascual** [comment]
This relates to the single-file html prepared by RTD. We no longer generate it, so I am closing
