### ISSUE TITLE
installation of taurus by pip

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#560]
Hello, linked to #552 I installed taurus with pip on a debian9 with Tango and pytango already installed.
When trying to install PyQt4, I got following error:
```
$ pip install PyQt4
Collecting PyQt4
  Could not find a version that satisfies the requirement PyQt4 (from versions: )
No matching distribution found for PyQt4
```
Do you know how to install this dependencies?

PS : I would like to install taurus ecosystem as much as possible with pip to allow virtualenv, that is why I avoid installation through apt-get

**Comment by cpascual** [comment]
Hi,
 PyQt4 is a PITA to install with pip for virtualenvs on linux (PyQt5 is fine, but Taurus still does not support it)

There are workarounds, though. The easiest one, is to install PyQt4 in the system via the repos and symlink it into your virtaulenv. For example, in my debian stretch this can be done with:

```
ln -s /usr/lib/python2.7/dist-packages/PyQt4 \
  <virtualenv_dir>lib/python2.7/site-packages/

ln -s /usr/lib/python2.7/dist-packages/sip.x86_64-linux-gnu.so \
  <virtualenv_dir>lib/python2.7/site-packages/
```

**Comment by cpascual** [comment]
Note that instead of linking, you can use a more coarse approach, which is creating your virtualenv with the `--system-site-packages` option.
This may defeat the purpose of the virtualenv in some cases, but it is fine (and easy) sometimes.

**Comment by cpascual** [comment]
Another alternative is to use Conda instead of virtualenv. See the conda-related coments in #408 

Note: I personally do not like the fact that there are no conda debian packages

**Comment by PhilLAL** [comment]
Ok, thank you.

**Comment by PhilLAL** [comment]
I reopened this ticket since I noticed that on Windows, dependencies are installed by python(x,y) while they can be installed through system package (or pip for at least some of them) on GNU/Linux.

Currently, default taurus version installed by pip is 4.1.1.
I wonder if the **complete** installation through `pip install taurus` is an option?
I mean installation of taurus and all (or a maximum of) dependencies.

As I understand it, it would at least need a `requirments` file (https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format), but there are probably some other constraints... 
By any chance, do you have some details on this option?

**Comment by cpascual** [comment]
AFAIK, fully installing taurus[taurus-qt] with pip (without adding a custom Package Index) is not an option. This is True regardless of the platform (Windows, GNU/Linux,...)

The reason is that PyQt4 (and PyQwt , Tango, etc) are not available in the default pip Package Index, and the build from source typically fails due to missing build-dependencies.

Conda is closer to the goal (although PyQwt5 and PyTango on windows are still blockers).

IMHO the simplest installation instructions for having a working taurus with qt and Tango support on windows are:
- install python(x,y)
- install PyTango 
- pip install taurus[taurus-qt]

**Comment by mrosanes** [comment]
Taurus can also be installed on Windows with the following dependencies after installing python-xy:
(Tested on Win7 Vagrant VirtualBox VM)

After doing a 'pip install --upgrade pip'
 
Dependencies installed with pip:
Cython==0.27.3
numpy==1.14.1
qtpy==1.3.1
Pillow==5.0.0
PythonQwt==0.5.5
guidata==1.7.6
scipy==1.0.0 (without dependencies: --no-deps)
spyder==3.2.7 (without dependencies)
guiqwt==3.0.3 (without dependencies)

Then Taurus4 should be installed correctly

**Comment by mrosanes** [comment]
On Win7 is not enough doing:

- install python(x,y)
- install PyTango
- pip install taurus[taurus-qt]

--

numpy upgrade is required (to version 1.14.1 for instance)
Otherwise this fails: from numpy.linalg import lapack_lite, _umath_linalg
ImportError: DLL load failed: The specified module could not be found.

Cython is required by guiqwt/guidata

--

The shorter recipe should be:


- install python(x,y)
- install PyTango
- install Cython
- install numpy
- pip install taurus[taurus-qt]

**Comment by PhilLAL** [comment]
Hi,
on this topic again, while reading the doc, I saw on http://taurus-scada.org/users/getting_started.html#dependencies :+1: 

`For GNU/Linux, it is in general better to install the dependencies from your distribution repositories if available.`

Is it still correct?

**Comment by cpascual** [comment]
Yes, I would say so.

**Comment by cpascual** [comment]
Nowadays,  it is possible to install all dependencies using conda, so I am closing this.

See https://github.com/taurus-org/taurus/wiki/Best-Practices-for-Taurus-4
