### ISSUE TITLE
Allow to set formatter in the taurus GUIs 

### ISSUE THREAD

**Issue by cmft** [taurus-org/taurus#563]
Nowadays Taurus allows to set custom formatters programmatically but the default widgets (taurusform, taurustrend, ...), use the default Formatter and does not allow to change it.

This enhancement propose:
- Add menu action to choice/set a Formatter
- Allow to configure the default Formatter  (e.g. via tauruscustomsetting)

**Comment by MikeFalowski** [comment]
Hey! What is status of this? I was just looking for engineering notification in taurusform.

**Comment by cpascual** [comment]
Oh, we forgot to close this ticket when we solved it in #564.

Basically now (in the develop branch / coming release) you can change the formatter in the following ways:

1. (GUI) set a custom formatter in TaurusForm (globally or per attribute) via a context menu option. TaurusForms will store this preference in their configs.
2. (GUI/PROG) use the `TaurusBaseWidget.onSetFormatter()` slot to set a custom formatter on any other widget
3. (PROG) set a custom formatter on any taurus widget (using `TaurusBaseComponent.setFormat`)
4. (PROG) set a custom formatter on any taurus class (by overwriting `.FORMAT`)
5. (CLI) set the defaultFormatter via a TaurusApplication command line argument (`--default-formatter`)
6. (CONF) set the defaultFormatter via tauruscustomsettings.DEFAULT_FORMATTER


Note that options 5 and 6 deal with the **default** formatter and therefore will affect all widgets (except those that explicitly changed it) and therefore should be used with great care and only with very generic formatters. In other words: Don not use those options unless you **really** know what you are doing. Option 4 should also be used with care if applied to a base class (since all child classes will be affected)
