### ISSUE TITLE
qtpy.QtWidgets module is missing

### ISSUE THREAD

**Issue by Aratar93** [taurus-org/taurus#581]
Hi all,

I installed taurusdesigner, and when I tried to start it, I got this message:

`MainThread     INFO     2017-09-26 15:33:59,117 TaurusRootLogger: Using "PyQt4" for Qt
Traceback (most recent call last):`
`File "/home/anad/.local/bin/taurusdesigner", line 7, in <module>    from` `taurus.qt.qtdesigner.taurusdesigner import main`
`  File "/home/anad/.local/lib/python2.7/site-packages/taurus/qt/qtdesigner/taurusdesigner.py", line 31, in <module>`
`    from taurus.external.qt import Qt`
`  File "/home/anad/.local/lib/python2.7/site-packages/taurus/external/qt/Qt.py", line 29, in <module>`
`    from .QtGui import *`
`  File "/home/anad/.local/lib/python2.7/site-packages/taurus/external/qt/QtGui.py", line 39, in <module>`
`    import qtpy.QtWidgets as __qtpy_QtWidgets`
`ImportError: No module named qtpy.QtWidgets`

Before that I had installed taurusdesigner's dependencies (I can attach whole installation script if it is necessary). 
Do you have any idea what the problem may be? What is qtpy.QtWidgets module and how to install it?

Best regards,
Aratar

**Comment by cpascual** [comment]
qtpy is a dependency of taurus since version 4.1. You need to install it.

See instructions in https://github.com/spyder-ide/qtpy

The best way to install it depends on your platform (e.g. for a Debian-based system, I suggest installing it with `apt-get install python-qtpy`).

If you have any trouble installing it, please report your full installation details (OS, versions of the installed dependencies, method of installation, etc).
