### ISSUE TITLE
what class do I need to import for a taurus component ?

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#610]
Hello,
when I want to use a taurus component, I did not find in the doc where to find the name of the class to import.
Currently, I found a walkthrough which is to grep the content of the classes in the repository to find  the class I want to use.

For instance, I found that TaurusLockButton is found into taurus.qt.qtgui.button so I use
`from taurus.qt.qtgui.button import TaurusLockButton`

However, I did not find this information in the page http://www.taurus-scada.org/en/latest/devel/api/taurus/qt/qtgui/button/_TaurusLockButton.html#taurus.qt.qtgui.button.TaurusLockButton but only in the file http://www.taurus-scada.org/en/latest/_modules/taurus/qt/qtgui/button/taurusbutton.html?highlight=TaurusLockButton

Did I miss something?

Thank you.

**Comment by cpascual** [comment]
Hi, if I understand correctly, you would like to find the info of the module in which a given class is in the API doc page for that class (e.g. because you arrived to that page via a link in a search), right?

In that case, you can find the info in the navigation part (on top of the page, above the inheritance diagram). For example, in :

http://www.taurus-scada.org/en/latest/devel/api/taurus/qt/qtgui/button/_TaurusLockButton.html

You can see this:
![image](https://user-images.githubusercontent.com/4115224/32484316-a71eb808-c39f-11e7-9f12-eb9e012ce1ca.png)

But that said, I agree in that it would be a nice improvement to show something like

> To import this class, use: `from taurus.qt.qtgui.button import TaurusLockButton`

Probably it can be done by adding it to the template in `<taurus>/doc/api_class.rst`
Would you like to propose a PR?  ;)

**Comment by PhilLAL** [comment]
I missed this because I first read PDF doc, and it was not inside. And when I read HTML doc, I did not notice this information.
With this information, it will be easier.
Thank you for your fast answer :)
