### ISSUE TITLE
taurusgui to link a widget to a TANGO attribute

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#611]
Hi,
I tried to design a taurus component with taurusgui to then compose a view with taurusdesigner.
However, I only find page http://www.taurus-scada.org/en/latest/devel/designer_tutorial.html and http://www.taurus-scada.org/en/latest/devel/taurusgui_newgui.html#taurusgui-newgui which do not explain how to link a taurus component to a TANGO attribute.

I understand taurusgui --new-gui allows to graphically create a widget linked to a TANGO attribute. 
How can I create this link? 
Do I have to do this through the taurusgui or do I have to do this in python file? 
Thank you.

**Comment by cpascual** [comment]
I think you got it the other way around... ;)

taurusgui allows you to create a final application by adding "panels" to it. Each panel contains a "widget" and will be allowed to be moved/docked within your final application. These widgets can be any Qt widget (including Taurus widgets).

Taurus widgets are QtWidgets which also provide a Taurus model API (setModel, getModel,...). The way of "linking a widget to a Tango attribute" is to set the model of the widget to the Tango attribute using its model name (e.g. `tango://a/b/c/d`). The highest-level Taurus widgets (e.g., TaurusForm, TaurusPlot, TaurusImageDialog,...) will also provide a way for the user to access this Taurus model API graphically at run time (e.g. in TaurusForm, you can use the "Modify Contents action" from the context menu). Also, when adding a panel to a TaurusGui, you can always go to "Advanced options" and set the model there (assuming that the widget is a Taurus one).

Now, regarding the Taurus Designer: taurusdesigner is what you use to create new Taurus widgets (typically by composing several other widgets) if the existing ones are not enough. In our experience, most of our GUIs are created using the existing widgets and taurusdesigner is seldomly needed. You could also use taurusdesigner for creating a full aplication, but in general I recommend to create widgets and insert them as panels in a TaurusGui because this will give you many extra things (even to the point that if you want to define "a very complex application", you can create it as a "very complex widget" and insert it as your only panel in a TaurusGui).

Finally, while the models can be set by setting the property in the designer, I recommend not doing so to avoid having the widget connected to the control system while in the designer. Instead, I recommend setting them programmatically (calling `.setModel()`)

**Comment by PhilLAL** [comment]
Thank you, I think I got it now. :)
