### ISSUE TITLE
signification of a black taurusLed

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#621]
Hello,
when I create a basic GUI with a taurusLabel and taurusLed, I got a black LED in some cases.
In my case, I use TANGO and in particular sys/tg_test/1 TangoTest device server.
When I link taurusLed to sys/tg_test/1/boolean_scalar, my taurusLed is green without any issue.
This is when I link taurusLed to sys/tg_test/1/boolean_spectrum[0] or sys/tg_test/1/boolean_spectrum[1] (i.e. a spectrum) that I got a black Led.

I do not find the signification of the black led in tango manual so I understand taurusLed could not find the value of sys/tg_test/1/boolean_spectrum[0]. 
Am I right?

How could I get the state of a my boolean value in this case?
Thank you.

**Comment by cpascual** [comment]
I think that your problem is that the attribute name that you are passing is invalid:
`sys/tg_test/1/boolean_spectrum[0]` is **not** a valid taurus attribute name (you cannot use slicing notation like this on a name). You could achieve what you intend with 
`eval:{sys/tg_test/1/boolean_spectrum}[0]`

Note that supporting slicing notation is already proposed in [TEP15](https://github.com/cpascual/taurus/blob/tep17/doc/source/tep/TEP15.md)

Also note that precisely today I merged a PR  (#617 ), which would allow to use arbitrary attributes with a TaurusLed. Basically the LED will represent the result of casting the value of the attribute with `bool`.

**Comment by PhilLAL** [comment]
Thank you for this details, I try the following syntax 
```
boolLedLabel.model, boolLedLabel.bgRole = 'eval:{sys/tg_test/1/boolean_spectrum_ro}[0]#label', ''
boolLedRead.model = 'eval:{sys/tg_test/1/boolean_spectrum_ro}[0]'
```
(I choose boolean_spectrum_ro because it changes often)
However, the led seems to alternate between green and black.
Do you have any idea why?

**Comment by cpascual** [comment]
If it changes to bklack it may be because in some situations the value is not working... but I cannot test it right now.
In the meanwhile I suggest that you open the LED demo ( run `taurusdemo` and open click the "Led" button). There you can play with different settings, and maybe it helps in understanding the problem.

**Comment by PhilLAL** [comment]
Ok, it seems taurusdemo works, and taurusled linked to sys/tg_test/1/boolean_spectrum_ro was just changing too often, but it works.
Thank you again. :)

**Comment by cmft** [comment]
IMO  `black` means  that the attribute is false (the led is off).  See this example:
```
taurusform "eval:True" "eval:False"
```

**Comment by PhilLAL** [comment]
Yes, it was my conclusion seeing taurusdemo.
