### ISSUE TITLE
Adding new unit

### ISSUE THREAD

**Issue by stanislaw55** [taurus-org/taurus#624]
Hi,
I've been trying to set unit in TaurusForm to `Sv` (Sievert). It's set in ConfigurationDialog but `gray` appears in the form.
AFAIK, there's a fixed registry of units used in Taurus. I've haven't found any tip how to add extra units to this registry. Any help will bee appreciated.

**Comment by cmft** [comment]
Hi @stanislaw55 ,
Taurus use  `pint` library and it use the International System of Units  for that reason you see `gray`. 

From wikipedia 
> The gray (symbol: Gy) is a derived unit of ionizing radiation dose in the International System of Units (SI)

Moreover, it seems that Pint is assuming the equivalent between Sv  and Gy that is not always true. For that reason I believe it is showing `gray` instead of `Sv`. 

I will try to  figure out how to avoid the "conversion".

**Comment by cmft** [comment]
I opened a issue in pint [#586](https://github.com/hgrecco/pint/issues/586)

**Comment by cpascual** [comment]
I thing a precission is required

> Taurus use pint library 

True

> and it uses the International System of Units for that reason you see gray.

Not so true. Pint does not enforce SI units. pint respects the units given by the user.

Here is what I think is really happening:
Sv is an operational unit for *equivalent dose* and *effective dose*. It is **not** physical quantity
Gy is the physical quantity for *absorbed dose*.

AFAIK, pint (and therefore taurus) deals with *physical quantities*. Since both are defined as "1 joule/kilogram", pint uses the physical quantity and defines Sv as an alias of Gy.

So, AFAIK , the issue is not related to SI vs non SI units, but with physical quantities vs operational ones.

**Comment by cpascual** [comment]
> I've haven't found any tip how to add extra units to this registry

Considering the replies above, I do not thing that this is longer relevant for you, but just for completitude, see #596 for a recipe on how to add units to the taurus unit registry.

**Comment by MikeFalowski** [comment]
Moreover, the `Gy` is not always "equal" `Sv`.
[In this thread](https://www.researchgate.net/post/What_is_the_difference_between_Sievert_and_Gray_A_practical_question_concerning_the_SI_units_for_ionizing_radiation) they mentioned that for alpha and neutron radiations value of `1 Gy` corresponds to `20 Sv` of equivalent dose, while for X-rays it corresponds to `1 Sv`.

**Comment by cpascual** [comment]
> Moreover, the Gy is not always "equal" Sv.

Of course. See [this comment](https://github.com/hgrecco/pint/issues/586#issuecomment-346329310)
