### ISSUE TITLE
usage of TaurusGui 

### ISSUE THREAD

**Issue by hayg25** [taurus-org/taurus#634]
I would like to understand  the usage of TaurusGui. Indeed, we are creating a list of widgets to create panels and we would like to combine them together. 
In TaurusGui this seems possible but I don't know how to select modules / Class ? Where should we put / install our classes to be accessible through TaurusGui ?

**Comment by cpascual** [comment]
First, you need your widgets to be importable from the GUI.
You can do this by making your module containing the widgets importable in general (e.g. by installing it somewhere listed in your PYTHONPATH), or by making it importable just to your GUI (copying the module in the your taurusgui config dir)

Then, you can create a panel containing an importable widget in different ways:

- In the config.py file for your GUI (see [e.g. how we add a QLineEdit in example01](https://github.com/taurus-org/taurus/blob/54c48a32d307148d4ebb848c59ea9b7749c2ba40/lib/taurus/qt/qtgui/taurusgui/conf/tgconf_example01/config.py#L105))
- Using the `Other...` button of the ["new panel" dialog](http://taurus-scada.org/en/latest/users/ui/taurusgui.html#creating-custom-panels)

Apart, if you want your widget(s) to be added to the "new panel" catalog (so that you do not need to use the `Other...` button), you can do so by listing them in the `EXTRA_CATALOG_WIDGETS` variable of your config.py file (see, e.g. [how we do it in example01](https://github.com/taurus-org/taurus/blob/54c48a32d307148d4ebb848c59ea9b7749c2ba40/lib/taurus/qt/qtgui/taurusgui/conf/tgconf_example01/config.py#L168))

Is this what you needed?

**Comment by hayg25** [comment]
Dear @cpascual, 
thanks for your answer. I have tried to put my modules in my PYTHONPATH,  and again cannot see them in the TaurusGui as expected using the Other... button of the "new panel" dialog.

**Comment by cpascual** [comment]
Ok let's try to do it step by step:

Create a new dir called `/tmp/foo` and create a file in it called `/tmp/foo/bar.py` with the following content:

```python
from taurus.external.qt import QtGui
class MyWidget(QtGui.QCalendarWidget):
    pass
```

Now, add the dir to the PYTHONPATH and check that the module is importable:

```
$> export PYTHONPATH=$PYTHONPATH:/tmp/foo
$> python -c 'import bar;print bar.MyWidget'
```

Now, in the same console,  launch a taurusgui (I use "example01", which is provided by taurus, but it can also be one created with `taurusgui --new-gui`):

```
$> taurusgui example01 --taurus-log-level=debug
```

... and in the gui now open the New Panel catalog and click the "Other" button. 

Now you should be able to enter `bar` as the module and select `MyWidget` as the class.

If not, please report whatever errors you see in the console

**Comment by hayg25** [comment]
Dear @cpascual , 
I have no problem running your example and using taurusgui --new-gui I could also see my classes. I believe I had a problem with my path definition. 
Again, many thanks for your fast feedback :)

**Comment by hayg25** [comment]
close

**Comment by hayg25** [comment]
close #634
