### ISSUE TITLE
WritableWidgets do not update in case of errors

### ISSUE THREAD

**Issue by sergirubio** [taurus-org/taurus#649]
The TaurusBaseWidget is writing a none value ( --- ) in case of receiving error events.

But the TaurusBaseWritableWidget is ignoring them, it processes Change and Periodic events but ignores the errors.

In a TaurusLineEdit, it may induce to error as user may keep trying to write values on a device that is not running at all. The widget should show that the device is not there anymore.

**Comment by cpascual** [comment]
I agree.
There is only one thing: the TaurusLineEdit (and probably most TaurusBaseWritableWidgets) should *not* lose their current text in case of error (because the current text may, e.g., be a set point which took the user some time to figure out ...) so what I propose is that we disable the widget in case of error and re-enable it later on.
This way we give the user feedback about something being wrong without losing the current text

**Comment by sergirubio** [comment]
Ok, sounds legit

**Comment by sergirubio** [comment]
As it is related to same widget, I'm pushing a solution to this issue on pr 673
