### ISSUE TITLE
TangoFactory does not keep updated the generic WeakRef

### ISSUE THREAD

**Issue by cmft** [taurus-org/taurus#706]
TangoFactory does not update the base  weakref (TaurusFactory) and implement its own references.

```     
  self._attrs = WeakValueDictionary()
  self._devs = WeakValueDictionary()
  self._auths = WeakValueDictionary()
```
You can see the problem here:
```
import taurus
tf = taurus.Factory() #TangoFactory
td = taurus.Device('sys/tg_test/1')
print len(tf._devs) # Returns 0
```

**Comment by cpascual** [comment]
Hi, @cmft , have you observed any problem related to this?

While I agree in that it would be more elegant if the base names were used, AFAIK it is not strictly a problem because:

a) those names in the base class ( `_attrs`, `_devs, ` and `_auths`) are private (and therefore just an implementation detail, never to be accessed from another class)

b) the only places where they are used in the base implementation are in the `getAttribute`, `getDevice` and `getAuthority` methods respectively, and `TangoFactory` fully reimplements those methods without even calling to the base implementation.

So IMHO the current implementation is ok (although it would be more elegant re-using the base names).

Note also that the names used by `TangoFactory` (`.tango_attrs`, etc) are *public*. Therefore, if we chose to refactor in order to use the base names instead, we should still keep the public ones available (maybe as properties accessing to the base names). I **personally** am undecided on whether it is worth doing such reimplementation...

**Comment by cmft** [comment]
Hi @cpascual ,
Apparently there is not any problem. I agree.

**Comment by cpascual** [comment]
Since it looks there is no time/motivation to change this, I am closing it.
