### ISSUE TITLE
Deprecate and eventually remove useParentModel feature?

### ISSUE THREAD

**Issue by cpascual** [taurus-org/taurus#734]
The TaurusBaseComponent.useParentModel is in principle a very attractive feature that allows the developer to write simpler code, etc...

But it is also quite complex to implement right, and certainly the current implementation in Taurus is very fragile and only works for some widgets and use cases. This has historically been the cause of much frustration and bug reports from new users (see e.g. [the use parent model limitation](http://www.taurus-scada.org/en/latest/_downloads/parentmodel_issue_demo.py), and #72, #676, #732  ) and I have the feeling that experienced taurus users tend to avoid using it at all.

From the taurus library developers point of view, it is my impression that in order to properly support the useParentModel on a given widget  (specially those containing taurus subwidgets), the developer must be aware of various subtleties and that it requires quite a lot of effort... and as a consequence many widgets do not properly support this feature.. 

In my opinion, this "half-baked" situation is worse (more confusing) than simply not having the feature available.

Therefore, unless someone is brave enough to attempt a full refactoring of this feature to make it robust and unobtrusive, I propose to mark it as deprecated and flag it for removal when the next major version of taurus is released.
 
What do you think?

**Comment by CorF4** [comment]
We are making use of this feature in our gui's since we have used the taurusdesigner quite a lot to create custom widgets. We would have many taurus widgets on a frame and when launching the ui-file we only need to set the model of the frame and not individually for each and every single taurus widget. So this feature is quite useful for us. Not having it would mean we need to get all the names of objects we created with the taurusdesigner and set the model for each of them. If there was an easy way to get the objects from the ui-file and just iterate over them, then I guess it would be ok.

**Comment by cpascual** [comment]
> We would have many taurus widgets on a frame and when launching the ui-file we only need to set the model of the frame and not individually for each and every single taurus widget. 

Yes. That is exactly the use case that the feature was designed for. 
But as I said, it has never worked 100% well and in practice most people ends up doing the workaround of explicitly setting the models of the children in the setModel method of the parent.

For example, in your case, you could reimplement the setModel method of the frame so that, after setting its own model, it explicitly sets the models of all of its children.

> we need to get all the names of objects we created with the taurusdesigner and set the model for each of them. If there was an easy way to get the objects from the ui-file and just iterate over them, then I guess it would be ok.

While this is certainly possible (you can use the `children()` and `findChildren()` methods of every QObject), in practice I think that most of the times it won't be that useful since you probably will want to set some specific model (based on that of the parent) to certain children (e.g. the frame may have model `a/b/c`, and one of its children have `a/b/c/d` and another child has `a/b/c/e`)... therefore an automatic "blind" iteration is not useful and you really need to know beforehand what are the subwidgets that you added in the designer.

**Comment by guifrecuni** [comment]
> therefore an automatic "blind" iteration is not useful and you really need to know beforehand what are the subwidgets that you added in the designer.

In some applications in the past, we have had this issue, and it was implemented using specific prefix and suffix for the children objects that provide such details, in order to know exactly that. e.g. while iterating with the children, you may find objects with names like: label_41, text_22, sub1_d, label_3, sub2_e, sub3_f, sub4_d, text_2, text_44, sub5_f, ... being "subN" just one of many possible conventions.
This approach will allow you to identify precisely which have to be configured and with which model, you could also name them like <prefix>_parent_sub, and then replace <prefix> by nothing, parent by parent model and sub by the last part of the model.

**Comment by CorF4** [comment]
I am trying to set the model for individual taurus widgets. I get the children of the frame and, since I specified the attribute name in the taurusdesigner I can get the "model"(=attrName) from that widget and set the Model to model+attrName. But appearantly there is something wrong with writable models, sometimes the application returns with seg-fault. Sometimes it loads all widgets correctly, but regularly crashes at some writable widget (like TaurusValueLineEdit or TaurusValueComboBox). No idea what's going on. Do you have an example code snippet of what you described for the workaround to avoid useParentModel??

**Comment by cpascual** [comment]
>Do you have an example code snippet of what you described for the workaround to avoid useParentModel?

Sure. here it is:

```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.base import TaurusBaseComponent
from taurus.qt.qtgui.util import UILoadable
from taurus.external.qt import Qt

@UILoadable()
class MyWidget(Qt.QWidget, TaurusBaseComponent):

    def __init__(self, parent=None):
        Qt.QWidget.__init__(self, parent=None)
        TaurusBaseComponent.__init__(self, 'MyWidget')
        self.loadUi()

    def setModel(self, model):
        TaurusBaseComponent.setModel(self, model)
        self.taurusLabel.setModel(model+'/state')
        self.taurusCommandButton.setModel(model)


if __name__ == '__main__':
    import sys
    app = TaurusApplication()
    
    w = MyWidget()
    
    model = 'sys/tg_test/1'
    w.setModel(model)
            
    w.show()   
    sys.exit(app.exec_())
```

And the corresponding ui file (saved in a ui subdirectory and named `MyWidget.ui`) is:

```
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>Form</class>
 <widget class="QWidget" name="Form">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>232</width>
    <height>116</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>Form</string>
  </property>
  <layout class="QVBoxLayout" name="verticalLayout">
   <item>
    <widget class="TaurusLabel" name="taurusLabel"/>
   </item>
   <item>
    <widget class="TaurusCommandButton" name="taurusCommandButton">
     <property name="Command">
      <string>switchstates</string>
     </property>
    </widget>
   </item>
  </layout>
 </widget>
 <customwidgets>
  <customwidget>
   <class>TaurusLabel</class>
   <extends>QLabel</extends>
   <header>taurus.qt.qtgui.display</header>
  </customwidget>
  <customwidget>
   <class>TaurusCommandButton</class>
   <extends>QPushButton</extends>
   <header>taurus.qt.qtgui.button</header>
  </customwidget>
 </customwidgets>
 <resources/>
 <connections/>
</ui>

```

**Comment by CorF4** [comment]
Thank you guys. This looks ok, but I run into some problems if I do some more complex model setting (in  threads)...I will open another issue for this so I don't spam this thread here.

**Comment by cpascual** [comment]
Hi, I think that my original question got buried in the specific discussion, so I launch it again, but in the form of "ultimatum"  ;-)  to be more expeditive :

Unless someone strongly disagrees, we will mark the "setParentModel" issue as deprecated

(please @taurus-org/integrators , some of you must for sure have some opinion on this!)

**Comment by teresanunez** [comment]
Hi @cpascual, IMO you can go ahead with this, I also think that is better not to have a feature than to have it working with a lot of restrictions.
