### ISSUE TITLE
[doc] TaurusLabel.setFgRole() method

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#737]
Hi,
testing the TaurusLabel functionnalities, I tried setBgRole and setFgRole.
I run a TANGO8 client with taurus 4.1.1 with a distant TANGO8 server.
```
python -c "import taurus; print taurus.Release.version"
4.1.1
```

When reading setFgRole documentation (http://taurus-scada.org/devel/api/taurus/qt/qtgui/display/_TaurusLabel.html?highlight=tauruslabel#taurus.qt.qtgui.display.TaurusLabel.fgRole), I saw several values that I wanted to test ( 'None', 'value', 'w_value', 'quality', 'state').

However, when using `eauReguleeUnite.setFgRole('value') ` in my code, I got this WARNING:
```
./RF_Canon.py 
MainThread     INFO     2018-04-13 13:14:55,264 TaurusRootLogger: Using "PyQt4" for Qt
MainThread     INFO     2018-04-13 13:14:55,335 taurus.qt.qtgui.icon.icon: Setting Tango icon theme (from /home/gauron/.local/lib/python2.7/site-packages/taurus/qt/qtgui/icon/)
MainThread     WARNING  2018-04-13 13:14:55,556 TaurusLabel: /home/gauron/Documents/travail/projets/ThomX/CC/depots/IHM/RFCanon/temperature.py:58: DeprecationWarning: setFgRole(value) is deprecated since 4.0. Use setFgRole(rvalue) instead
  eauReguleeUnite.setFgRole('value')
```

I did not succeed to observe a difference between these values 'None', 'value', 'w_value', 'quality', 'state'.

How should I use this method setFgRole ?
Thank you.

**Comment by cpascual** [comment]
Hi. Do not worry about the warning.
It just recomends to use "rvalue" instead of "value" as the parameter for setFgRole.

If you want to see the effect of these settings in an easy way, run `taurusdemo` and choose the "label" demo.

For example, the following snapshot shows the effect of different configurations for background and foreground roles for the same attribute:

![image](https://user-images.githubusercontent.com/4115224/38737276-043bd10a-3f2f-11e8-9cb5-c541a8137482.png)

**Comment by cpascual** [comment]
Note: this was one of the things that saw some improvements in the last release, so I recommend you to update to taurus 4.3.1

**Comment by PhilLAL** [comment]
Thank you, I updated my version. :)
