### ISSUE TITLE
Taurus performance when setting tango models

### ISSUE THREAD

**Issue by CorF4** [taurus-org/taurus#741]
Hello,
this is a question: In our applications we need to set the models on around 30-40 widgets when the gui is opened. This takes around 4-5s usually. In the case where we have a tab with ~30 widgets that need to have a model set, it takes about 2s until the switch to that tab happens. If there are less widgets to be set, it's faster. My question is: is there a way to speed this up? Is there a difference between tango models and epics models? We remember when someone was presenting a taurus gui with EPICS the gui seemed to open instantly, at least much faster than our gui's with tango.

Thanks a lot!

**Comment by cpascual** [comment]
First of all, please note that Tango 9 introduced some sleeps during event subscription which were causing excessive connection times in Taurus GUIs that set many models at once. This has been addressed in [this PR to Tango](https://github.com/tango-controls/cppTango/pull/415) , which is already merged in the tango9-lts branch but not included in the Tango 9.2.5 release (it will be available in the next release, I guess). If you do not want to wait, you can use said branch or patch your sources by cherry picking.

Apart from that, here are some strategies that you can use to alleviate the problem:

- You can use the ["delayed subscription" hack](https://github.com/taurus-org/taurus/wiki/Recipes#delay-or-disable-tango-events-in-taurus) **Warning, this is experimental, it may break some widgets**
- Assuming you set all the models in a method named `foo`, instead of calling it directly, you can call it as `QTimer.singleshot(0, foo)`. This will delay delay this task unti all the Qt window events are processed, and therefore the GUI will feel smoother. In some cases, it may also help inserting calls to `QApplication.processEvents`in `foo`. See also [other tricks](https://doc.qt.io/archives/qq/qq27-responsive-guis.html) 
- You can give feedback to the users about what's going on (use of progress bars, splash screens, etc). TaurusMainWindow and TaurusGUI already provide splash screen API and a message bar.
- You can use threads to parallelize setting of the models the models...  but, as you know (#739), this can be problematic.

**Comment by CorF4** [comment]
Thanks a lot! This is really helpful!
