### ISSUE TITLE
Support referencing to attribute slices in the model name

### ISSUE THREAD

**Issue by CorF4** [taurus-org/taurus#751]
Hello,
I noticed when using the TaurusJDrawSynopticsView class that there is nothing foreseen to handle spectrum attributes with a given index (idx). In Tango it works for a DevState type if one puts [idx] at the end of the attribute name. Could it be useful to support this in taurus as well? And for all kind of numeric spectrum types?
I don't know how much this is actually used, but for my case I certainly need to make this work.

**Comment by cpascual** [comment]
Hi @CorF4 this would be a welcome feature indeed. But instead of solving it just for TaurusJDrawSynopticsView, see the related [TEP15](http://www.taurus-scada.org/tep/?TEP15.md) which, if implemented, could solve this in a very generic way (at model level). 

Actually, the implementation of TEP15 should be quite easy (I think that it can be done in a few lines in `TaurusModel.getFragmentObj`): the hardest part is actually to agree on the syntax (TEP15 draft proposes 3 alternatives). We just had had not time/interest to discuss it, but if you are interested in the feature, let's open the discussion among @taurus-org/integrators and anybody else interested. Once agreed, I can propose the implementation according to it.

PS: as a workaround, you can use eval for slicing. For example, for getting the first element of the `sys/tg_test/1/wave` attribute , you could use `eval:{tango:sys/tg_test/1/wave}[0]`:
```python
print taurus.Attribute("eval:{tango:sys/tg_test/1/wave}[0]").read().rvalue
# --> 0.406736319852
```

**Comment by cpascual** [comment]
> let's open the discussion among @taurus-org/integrators and anybody else interested. Once agreed, I can propose the implementation according to it.

Ok, after some discussions at ALBA and since nobody else expressed a preference, we will implement this using the first option from TEP15 (brackets syntax). I'll create a PR ASAP (the goal is to have TEP15 approved before the Jul18 release)

**Comment by cpascual** [comment]
Hi @CorF4 , could you please test if the implementation of #764 solves this issue for you?

**Comment by cpascual** [comment]
FYI, I did my own test with #764 (TEP15) and it worked for me:

```
$ cat syntest.jdw
JDFile v11 {
  Global {
  }
  JDSwingObject {
    summit:33,74,324,183
    origin:179,129
    fillStyle:1
    name:"sys/tg_test/1/wave#rvalue[0]"
  }
}

$ devenv python -m taurus.qt.qtgui.graphic.jdraw.jdraw_view syntest.jdw
```
