### ISSUE TITLE
tabWidget object hosting other GUIs

### ISSUE THREAD

**Issue by almarass** [taurus-org/taurus#763]
Hi,
I would like to host and visualize another GUI, defined in a different Python script (like PANIC GUI), in one of the tabs of a tabWidget object belonging to the current GUI.
Is it possible?

I already succeeded in such task using taurusGUI, but I would like to solve it programmatically.

Thanks,
Alex

**Comment by cmft** [comment]
Hi @almarass,
AFIK it can be done but in the past we got performance problems with some applications, panic was one of them ( [Vacca GUI](https://github.com/tango-controls/VACCA) is an example of that). So, my recommendation is to add then as external applications (you can locate the launcher in the right bar "jorg bar" or in the menu)

**Comment by almarass** [comment]
Hi Carlos,
if I understand correctly, you are saying that the efficient way to use
panic gui from another hosting gui is to launch it as an external
application from taurusGUI.
Anyway, if possible, I would like to try the other way; how may I proceed?

thanks,
Alex

2018-06-15 15:57 GMT+02:00 Carlos Falcon <notifications@github.com>:

**Comment by cmft** [comment]
Hola @almarass ,
Taurus has an example taurusgui with custom setup, you can see it [here](https://github.com/taurus-org/taurus/blob/develop/lib/taurus/qt/qtgui/taurusgui/conf/tgconf_example01/config.py)

For add a panel with the PANIC gui you can add this piece of code in the config.py of your taurusgui 
```
from taurus.qt.qtgui.taurusgui.utils import PanelDescription
panic = PanelDescription('PANIC', classname='panic.gui.AlarmGUI', area=None)
```

**Comment by cpascual** [comment]
Hi @almarass : if you do not want to use a TaurusGUI, you can also do it the standard Qt way by treating the GUI you want to embed in your tab just as any other QWidget. But note that some GUIs may behave oddly when treated this way. In particular some GUIs may assume that their QMainWindow is a top widget (i.e. without parent) and also may try to do stuff with the QApplication singleton which may not work well when embedded into another GUI.

**Comment by cpascual** [comment]
Hi, I understand that the original question is answered, so I close it. 
@almarass , please feel free to reopen if you need more clarifications

**Comment by almarass** [comment]
Hi Carlos,
after a while I take up the issue again: sorry for the delay.
I tried the following code to host in a main GUI either PANIC GUI or Tango
logviewer GUI, not using TaurusGUI. While it works perfectly hosting a
standard xterm, it shows both PANIC GUI and logviewer GUI in separate
windows.

Any idea to explain this behaviour?
Is it possible to solve the problem in any different way?

Thanks,
Alex

#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
from PyQt4.QtCore import *
from PyQt4.QtGui import *

class embeddedTerminal(QWidget):

    def __init__(self):

        QWidget.__init__(self)
        self.resize(800, 600)
        self.process  = QProcess(self)
        self.terminal = QWidget(self)
        layout = QVBoxLayout(self)
        layout.addWidget(self.terminal)

        self.process.start(
            #'xterm',

'python',['/home/tango-cs/Downloads/PANIC-6.5.1/panic/gui/gui.py',
            #'/home/tango-cs/src/tango-9.2.5a/lib/java/logviewer',[
            '-into', str(self.terminal.winId())]
        )

if __name__ == "__main__":
    app = QApplication(sys.argv)
    main = embeddedTerminal()
    main.show()
    sys.exit(app.exec_())





2018-07-02 17:02 GMT+02:00 Carlos Pascual <notifications@github.com>:

**Comment by cpascual** [comment]
I am not sure that I understand what you want to do with your snippet.

If I run your snippet with the xterm line uncommened and the panic one commented, I get 2 windows: an empty one and an xterm... so I do not see it "working" as an embedded terminal.

Anyway... AFAIK, you can only truly embed  an application on a pyqt GUI (as in having the app running in a tab of your GUI), if that application exposes itself as a pyqt widget. In such case you just need to import the app class and treat it as another qtwidgetin your GUI.

Otherwise, your only option is to add a launcher of the application in your GUI (but that won't run in a tab, but as an independent window). This is what we do with [ExternalAppAction](http://taurus-scada.org/devel/api/taurus/qt/qtgui/util/_ExternalAppAction.html) (note that it can be used in any taurus application, not necessarily a TaurusGui)

Finally, if you do not want to use taurus at all (but then why asking here?   ;)  ), you can easily adapt the implementation of ExternalAppAction](http://taurus-scada.org/devel/api/taurus/qt/qtgui/util/_ExternalAppAction.html) to remove the taurus dependencies (it is almost a pure Qt class already)

**Comment by almarass** [comment]
Hi Carlos,
sorry for the delay in the reply, but unexpectedly my computer suffered a
damage.
I tried the code snippet (attached) on several machines and it worked with
xterm, in the sense that an xterm appears embedded as a widget of the main
window (see attached screenshot).

The configuration is as follows:
Ubuntu 16.04
Python 2.7.12
Qt version 4.8.7
PyQt version 4.11.4

I do want to use Taurus, since all my project's GUIs have been built using
Taurus.

If I understand correctly it is possible to launch the available Tango
applications PANIC and logviewer, but not to embed them as widgets in a
main GUI.
In this case, I'll proceed with launchers to run them as independent
windows, as you suggest.

Thanks,
Alex



2018-08-16 12:47 GMT+02:00 Carlos Pascual <notifications@github.com>:

**Comment by cpascual** [comment]
> If I understand correctly it is possible to launch the available Tango applications PANIC and logviewer, but not to embed them as widgets in a main GUI. In this case, I'll proceed with launchers to run them as independent windows, as you suggest.

I cannot say for sure since I do not know the details of PANIC and logviewer....

For example, AFAIK, Panic is implemented as a (heavily-customized) TaurusGUI and as such it may (or may not) be possible to use it as a widget within another taurus application (it depends on the API it exposes... maybe @srubio can clarify it)
