### ISSUE TITLE
TaurusValueCheckBox is not getting updated

### ISSUE THREAD

**Issue by daneos** [taurus-org/taurus#768]
I have a TaurusValueCheckBox connected with a read-write boolean attribute. I can change the value of the attribute with the checkbox, but it's not getting updated when the value is changed outside of the GUI.
I've checked the events, and these are working fine.
Taurus version is 4.3.1

**Comment by cpascual** [comment]
I tested and I got the expected behaviour, so I am assuming that your issue is actually a confusion about the "expected behaviour" (please read on, and if that is not the case, please report it as a bug and provide a snippet of code so that we can reproduce the problem):

Note that the `TaurusValueCheckBox` is a `TaurusWritableWidget`, and as such, by design it is **not supposed to change its check state if there are external changes to its model**. Instead, it should show a "Pending Operation" (in the case of the checkbox this is indicated by a blue text - or blue `!` next to the checkbox in the case of a TaurusForm) and reflect this in the tooltip:

![image](https://user-images.githubusercontent.com/4115224/42227242-56a4af38-7ee1-11e8-959c-1421f48a0b9e.png)

Why is this?
The reason is that on a GUI you may have many checkboxes and other write widgets and you may be selecting a given subset of them to be on a certain state... and you don't wnat them "amgically switching" while you try to set the right configuration. Instead, eventually syou may want to apply changes to those whose displayed state does not correspond to the applyed state (this is the definition of a pending operation). This is also the reasoning behind the decision of not "autoapplying" by default on write widgets.

To read more about the pending operations, see: http://taurus-scada.org/users/ui/forms.html#writing-to-attributes .

**Comment by daneos** [comment]
This explains a lot, thanks. You are right about the confusion, and the outcome I'm getting is indeed the expected behaviour.
