### ISSUE TITLE
TaurusPlotConfigDialog not intuitive UX

### ISSUE THREAD

**Issue by KrystianKedron** [taurus-org/taurus#772]
In TaurusPlotConigDialog after pressing "enter" the dialog will close and the user will lose all changes in the configuration. The more intuitive is that TaurusPlotConigDialog stores the configuration in this situation. We can achieve this in two ways. The first is to add an additional button with focus, for example the name "Ok" or change the focus from "Close" to "Apply". The second scenario has more impact on UX, because in this case we do not close the window. You can see this problem and suggestions for its solution in the screenshot. I realize that experienced Taurus users have become accustomed to this, but a lot of users in SOLARIS have reported this problem. What do you think?

SOLUTION 1:
![solution1](https://user-images.githubusercontent.com/10261686/43065798-3b2b2642-8e63-11e8-96ba-2edf8c0f0c2f.PNG)

SOLUTION 2:
![solution2](https://user-images.githubusercontent.com/10261686/43065799-3b58ab58-8e63-11e8-9dab-2f750d15343e.PNG)

**Comment by cpascual** [comment]
Hi, I cannot reproduce the problem with the latest develop version or the latest stable version (4.3.1): in my case, pressing ENTER applies the changes (if any) but does not close the dialog.

The difference in you case may be due to any of these 2 causes:

1.maybe  you are using an old version of Taurus (I am not sure, but I vaguely recall having this problem some time ago and it being fixed... but I cannot find anything in the issue tracker)
2. maybe it has to do with the window manager or the desktop theme selecting the ok button by default (mine doesn't).

Can you please check if you can still reproduce your problem using the latest version (4.3.1). If so, please provide step-by-step instructions on how to do it.

**Comment by KrystianKedron** [comment]
I use Taurus 4.3.1 from develop branch.

You are right. This is connected with X envoriment. In the pass we don't have this issue because we use GNOME Desktop and we change to MATE. 

I test this and in GNOME the order of the button is different. Like in the screenshout.
![gnome](https://user-images.githubusercontent.com/10261686/43072294-e0226aa4-8e75-11e8-81bb-5fd887d10d51.PNG)

In MATE default button is 'CLOSE'
![mate](https://user-images.githubusercontent.com/10261686/43072296-e2e24520-8e75-11e8-927b-a81ac6c7094c.PNG)


To achieve second situation in my first post I declare the button order in the code, by adding this line on to init the TaurusPlotConfigDialog class: 
`self.ui.buttonBox.button(Qt.QDialogButtonBox.Close).setAutoDefault(False)
 self.ui.buttonBox.button(Qt.QDialogButtonBox.Close).setDefault(False)
 self.ui.buttonBox.button(Qt.QDialogButtonBox.Apply).setAutoDefault(True)
 self.ui.buttonBox.button(Qt.QDialogButtonBox.Apply).setDefault(True)`

Maybe this is good idea to declare this order in Taurus?

**Comment by cpascual** [comment]
> Maybe this is good idea to declare this order in Taurus?

Yes. I agree. Even if as a general rule we prefer not to interfere with the defaults from the themes, in this case I think it makes sense. 

To speed up things, could you please submit a PR against the develop branch?
(see https://github.com/taurus-org/taurus/blob/develop/CONTRIBUTING.md).
