### ISSUE TITLE
Event subscribtion

### ISSUE THREAD

**Issue by stanislaw55** [taurus-org/taurus#789]
Hello Taurus community

recently I've encountered strange problem with Taurus' event system. 
I have few motors controlled via Sardana. Using Jive, I've set up polling for each axis. After that, I've tested periodic events with simple script and they are received as expected. ut the main gaol was to use GUI based on Taurus. 

In GUI, by adding `Listener`s to `Attribute`s, expected behaviour is the GUI to update values every 5 seconds, which is polling period for most of attributes. However, after little investigation, I've realised that only one attribute of each motor is updated. Only for this one attribute, Taurus' receiving periodic events, for every one else, Taurus is subscribing to Change Event. I would like the GUI to subscribe only to Periodic Events.

After thorough investigation, that specific attribute has nothing special compared to the rest of them. Polling period is set correctly, events are not configured, apart from Periodic. I've checked that using Jive.
My question is: in which direction I should investigate further? Is it connected to some configuration options? Maybe it is buggy behaviour?

**Comment by cpascual** [comment]
In principle, taurus does not subscribe to Tango periodic events, only to change, configuration and error events. Subscription to periodic events is not implemented yet but it is on the TO-DO list (see #654 )
Since you report that some attribute is subscribed to periodic events, I suspect that it may be that precise widget doing it specifically (or that maybe they are not periodic but change events?)

If you feel brave enough to dive into the event subscription code of `taurus.core.tango.TangoAttribute`, you can try to implement #654 . But note that it is a delicate and complex part of the code.

**Comment by stanislaw55** [comment]
Hello @cpascual 
thank you quick answer. My assumption of event types was taken from `TaurusTypeEvent` enum. Type of received events was `0`, which I imagine is Change Event, according to that enum. The specific attribute which received events periodically had them of type `2` which is Periodic, again according to that enum. 

Could you confirm that this assumption was or wasn't correct?

AFAICS, I'm not using special widget, just ordinary `TaurusLabel`.

Unfortunately, I don't fell skilled enough to implement such feature.

**Comment by cpascual** [comment]
Ok. I guess I understand what's going on: you are seeing **taurus** periodic 
events (probably coming from the internal taurus polling). They are not 
**Tango** Periodic events. 

IMHO we should make that TangoAttribute also subscribes to Tango periodic 
events. But this is not trivial because we need to also handle the automatic 
unsubscription when destroying, and also we should discuss wether a re-
subscription mecanism or a delayed-subscription mechanism is required (as we 
have for the change events). Also we should consider the other tango event 
types, and decide if we want to also subscribe to them... and if so, how to 
map their types to the taurus tevent types...

So this will need some time to discuss... and probably the discussion won't 
happen before the end of the summer since many people is on holidays now...

**Comment by stanislaw55** [comment]
Ok, that would be sense and clarify many things. While I recognize this issue as complex and worth discussion, I would like to know how to enable Taurus internal polling for all attributes (apparently, now it's just enable for one of them, dunno why). Is that mechanism in Taurus or it's just pure automatic process?

**Comment by cpascual** [comment]
Taurus autoenables it when the device does not declare that it will emit events and no server-side tango polling is configured
