### ISSUE TITLE
copying Model from GUI

### ISSUE THREAD

**Issue by PhilLAL** [taurus-org/taurus#803]
Hi,
we uses Taurus for TANGO and we recently had a request from our users I am not able to answer:
on a GUI, is there a way to copy the origin of a value? 

For instance, if a TaurusLabel displays the current ER/PS/DP.01/current of ER/PS/DP.01, the user could click on the TaurusLabel to get the value ER/PS/DP.01/current (the model).

Reading the issues to find if something exists, I found https://github.com/taurus-org/taurus/issues/124 which talk about a copy functionnality but it seems old and I'm not sure this is exactly what we need.

Is there something already existing to do this?

Regards.

**Comment by cmft** [comment]
Hi @PhilLAL ,
There is not  feature to get the model directly in a GUI (I'm imaging that the "drag" option over the label could provide it ), but the taurusgui provides (for the moment  (there is a plan to remove it) and only for tango attributes) a context menu (right button) "Configuration-->All..." and there you can find  the attr. "fullname" (in fact it is a normal_name of the attribute since it does not follow fqdn).

Hope this help you.

**Comment by PhilLAL** [comment]
Thank you Carlos. :)
