### ISSUE TITLE
Taurus eval using function defined in another python module

### ISSUE THREAD

**Issue by almarass** [taurus-org/taurus#825]
Hi,
I am trying to visualize an enum attribute value via a TaurusLed.
The enum attribute value is read via the function cambia1() defined in foo2.py as follows:

n=0

def cambia1()
    import PyTango
    import taurus
    dishManager = PyTango.DeviceProxy("//151.97.17.82:10000/mid_dish_0001/elt/master")
    x = dishManager.read_attribute('setMaintenanceModeProgressStatus')
    a = x.value
    global n

    if a==0:
       n=0
    elif a==3:
       n=1
    else:
       n=0
    return n

Such function is called by a main python module as follows:

from taurus.external.qt import Qt
from taurus.qt.qtgui.display import TaurusLed

def toLedName(self, status=True, color=None, inverted=None):
    """Gives the led name for the given status and color. If status or
    color are not given, the current led status or color are used.

    :param status: the status
    :type  status: bool
    :param color: the color
    :type  color: str
    :return: string containing the led name
    :rtype: str"""
    if status is None:
        status = self._ledStatus
    if color is None:
        color = self._ledColor
    if inverted is None:
        inverted = self._ledInverted
    if inverted:
        status = not status
    status = status and "on" or "off"
    return self._ledPatternName.format(color=color, status=status)

def main():
    import sys
    import taurus.qt.qtgui.application
    Application = taurus.qt.qtgui.application.TaurusApplication

    app = Application.instance()
    owns_app = app is None

    if owns_app:
        import taurus.core.util.argparse
        parser = taurus.core.util.argparse.get_taurus_parser()
        parser.usage = "%prog [options] <full_attribute_name(s)>"
        app = Application(sys.argv, cmd_line_parser=parser,
                          app_name="Taurus led demo", app_version="1.0",
                          org_domain="Taurus", org_name="Tango community")

    model = "eval:@foo2.*/cambia1()"
    #model = "eval:@foo1.*/cambia()"
    w = Qt.QWidget()
    layout = Qt.QGridLayout()
    from taurus.qt.qtgui.display import TaurusLed
    TaurusLed.toLedName = toLedName
    led = TaurusLed()
    led.setModel(model)
    w.setLayout(layout)

    led.setOffColor("RED")
    layout.addWidget(led)
    w.show()

    if owns_app:
        sys.exit(app.exec_())
    else:
        return w

if __name__ == '__main__':
    main()

As a result I get the WARNING: EvaluationFactory: Problem importing "foo2"

If I replace the function cambia1() with the function cambia() defined in the python module foo1.py as follows:

numero=1

def cambia():
    import time

    time.sleep(1)
    global numero
    numero = (numero+1) % 2
    return numero

It works perfectly.

Which is the problem?

Thanks,
Alex

**Comment by MikeFalowski** [comment]
I'm not sure exactly what is the reason of this warning here, but I would propose you to create an attribute in device with such logic, giving you `false` or `true` or one of the `DevState` states for workaround (facadedevice library is perfect for this).

Anyway your post is very hard to read and you could consider to refactor it. Moreover I'm not sure if you aware of it but it is recommended to use `import` at the beginning of the file (e.g. refer to PEP8). You can also use `import tango` instead of `import PyTango`  if you have PyTango>=9.2.0

**Comment by almarass** [comment]
I forgot a colon in function cambia1() definition...
Sorry for the trouble

**Comment by cpascual** [comment]
Hi @almarass . Before looking at the actual question, let me make one comment:

I would recommend **against** using PyTango.DeviceProxy while in a taurus application. In fact, it is generally better to avoid importing PyTango / tango at all if you are using taurus. Note that if you use `taurus.Device` with a tango model, you get at `TangoDevice` instance which **also** exposes the API of an underlying `PyTango.DeviceProxy`. Also note that if you want to read an attribute, it is simpler to use `taurus.Attribute`
So, for completitude, instead of 
```python 
import PyTango
import taurus
dishManager = PyTango.DeviceProxy("//151.97.17.82:10000/mid_dish_0001/elt/master")
x = dishManager.read_attribute('setMaintenanceModeProgressStatus')
a = x.value
```

I would do something like:

```python 
import taurus
x = taurus.Attribute("//151.97.17.82:10000/mid_dish_0001/elt/master/setMaintenanceModeProgressStatus")
a = x.read().rvalue
```
I would do

**Comment by cpascual** [comment]
And a final note: as @MikeFalowski suggested, instead of manually changing the led color, I would consider having an attribute that returns tango `DevState` values if applicable. In that case, the led will switch the color by just setting the model.
