### ISSUE TITLE
tango gui custom panel get list model/attributes

### ISSUE THREAD

**Issue by pierreH23** [taurus-org/taurus#838]
Hello !
last year I was writing some custom widgets ... with the help of this forum, I was finally able to write one and to run it with the 'Other' menu in 'taurusgui'?
But I meet another difficulty : I'd like to get the list of 'attributes/models' given with the 'Advanced Setting' dialog in my code (for now I hard code the Taurus attribute/model), control if the type is compatible, ...
I inspected the source code but didn't find any solution with my competence level 
Many thanks
Pierre Héricourt
CELIA/CNRS
Université Bordeaux / France

**Comment by cpascual** [comment]
Hi @pierreH23 , I am not sure to understand your question.

This is what I think I understood:

1.- You have your own widget
2.- You run a TaurusGui  and open the "New Panel" Dialog, where you use the "Other" button to select your own widget
3.- You then use the "Advanced setings" button to select a list of models

...and now, if I understand correctly, you want to access the list of models that are listed in the "Model" box of the "advanced settings" dialog.

If you want to get it **before** you click on the Finish button of the "New Panel" Dialog, then it is not possible, because your widget does not even exist at this point. Your widget is only instantiated when you click on the "Finish" button, and the model list is then passed to it with a call to your widget's `setModel()` method.

On the other hand, if you are ok with getting it **when** the panel is created (i.e. when you click the finish button), you just need to do your checks in your `setModel` method. Or you can also use your widget's `getModel`/`getModelObj` in any other part of your code.

If you need more control than that over the model selection in your widget, I suggest add an action to your widget to show a (possibly customized) `ModelChooser` dialog and you connect it to your `setModel` method (see, e.g. how the TaurusForm does it). Then, you can use this dialog to set the models in your widget without having to use the New Panel --> Advanced Settings for that.

**Comment by pierreH23** [comment]
Hi Carlos !
I am a little ashamed: so there were only two lines to write to enjoy python inheritance !
My widget runs now perfectly without any hardcoding : I added the 'setModel' method and wrote initialization code in it.
Many thanks !
Pierre
