### ISSUE TITLE
taurus_pyqtgraph need taurus 4.5.2, but avalieble 4.5.1 only

### ISSUE THREAD

**Issue by tre3k** [taurus-org/taurus#873]
I try to install taurus_pyqtgraph, but can't satisfy requirements about version of taurus. It need a 4.5.2 version, but available for installation only 4.5.1. Will it work if i change requirements in setup.py file?

pip install --user git+https://github.com/taurus-org/taurus_pyqtgraph.git
Collecting git+https://github.com/taurus-org/taurus_pyqtgraph.git
Cloning https://github.com/taurus-org/taurus_pyqtgraph.git to /tmp/pip-IkWXma-build
Collecting taurus>=4.5.2 (from taurus-pyqtgraph==0.1.0a0)
Could not find a version that satisfies the requirement taurus>=4.5.2 (from taurus-pyqtgraph==0.1.0a0) (from versions: 2.0.0, 2.1.0, 2.1.1, 3.0.0, 3.1.0, 3.2.0, 3.3.0, 3.3.1, 3.4.0, 3.6.0, 3.7.0, 3.7.3, 4.0.0, 4.0.1, 4.0.3, 4.1.1, 4.3.0, 4.3.1, 4.4.0, 4.5.1)
No matching distribution found for taurus>=4.5.2 (from taurus-pyqtgraph==0.1.0a0)

**Comment by cpascual** [comment]
Hi, sorry about this mess. It is our fault.
The reason is that taurus_pyqtgraph is still in pre-1.0 stage and we have not been careful about its versions.

You have 2 options:

a) install the latest taurus (2.5.3a0) from the develop branch, or
b) Install [the 0.1.0a version of taurus_pyqtgraph](https://github.com/taurus-org/taurus_pyqtgraph/tree/0.1.0a0), which works with tauru>=4.3.0
