### ISSUE TITLE
plot performance

### ISSUE THREAD

**Issue by kklmn** [taurus-org/taurus#888]
Hello,

We do many fly scans with each one of ~3000 points and ~30 sec duration. I notice that:
 
1) The plotting is slower than the actual scanning. When we do many repeats, we have to wait for the plotting for quite some time, maybe 20 min more.

2) The plotting speed decreases as we progress with scan repeats. I suspect that each new point commands replotting and when there are many points, the replotting becomes much slower.

Questions.

Can some setting make it faster? Like selecting OpenGL as a plotting backend?

Can we decimate plotting points or restrict their frequency of arrival?

Can we freeze the previous curves (points) and only replot the current curve or even only the last point?

Thank you in advance for any advice!

Taurus 4.4.0

**Comment by reszelaz** [comment]
Thanks for the report @kklmn! We will try to reproduce it here at Alba.

You use the scan plot launched from the expconf, right?
Could you tell me how many channels do you plot at the same time? I suppose you plot them against the moveable and not against the scan point?

**Comment by kklmn** [comment]
Yes, this is from a Sardana macro, using an expconf. We plot 3 channels but I also tried 1. And yes, it is against the movable.

**Comment by cpascual** [comment]
Hi @kklmn ,
> Can some setting make it faster? Like selecting OpenGL as a plotting backend?
I understand that you are using the trend provided by Qwt... AFAIK there is no choice of backend with Qwt.
Once we manage to replace the Qwt trend by an implementation based intaurus_pyqtgraph this should indeed be possible.

> Can we decimate plotting points or restrict their frequency of arrival?

The plot of the scan is implemented by a `TaurusTrend` Qwt widget. This widget incorporates a feature for limiting the rate of replots (see [TaurusTrend.rescheduleReplot](http://taurus-scada.org/devel/api/taurus/qt/qtgui/qwt5/_TaurusTrend.html?highlight=trendset#taurus.qt.qtgui.qwt5.TaurusTrend.rescheduleReplot))
The problem is that it is currently only used when the `TaurusTrend.xIsTime()==True` (which is not the case if you plot against a moveable). I think that it should not be too hard to extend it so that it is also used when `TaurusTrend.xIsTime==False` 

The only thing is that IMHO it makes more sense to concentrate the scarce development efforts into  the taurus_pyqtgraph implementation of TaurusTrend, rather than in the soon-to-be-removed Qwt implementation... but if you or someone else is motivated to propose a PR along the lines suggested above, it would be very welcome.

> Can we freeze the previous curves (points) and only replot the current curve or even only the last point?

I do not think so (at least not without a lot of new custom code)

**Comment by cpascual** [comment]
Hi @kklmn can I consider this question closed?

**Comment by kklmn** [comment]
Yes. I have made a tabbed widget with several pyqtgraph plots and now have not only raw signals but also on-the-fly EXAFS analysis and have full control over the plotting performance.
