### ISSUE TITLE
default plot settings

### ISSUE THREAD

**Issue by kklmn** [taurus-org/taurus#901]
Hello,

Where can I set default plot settings for line colors and symbols?
I want to see my lines in the same colors as displayed by electrometers. When I change them in plot settings, they don't preserve in a new plot.

Thanks!

**Comment by cpascual** [comment]
What kind of plot are you working with?
How do you lauch it?

If it is a "classic" TaurusPlot implemented with PyQwt5 (e.g. you are launching it with the `taurusplot`launcher), you should be able to open the context menu and "Save current settings" to a file, which you can then use (at launch time with the `--config` option ) or at run time with the context menu ("Retrieve Current Settings").

Or, if your plot is part of a `TaurusGui`, the settings should be saved on close and restored on launch automatically.

Of course you can also access this programatically. See the API in [BaseConfigurableClass](http://taurus-scada.org/devel/api/taurus/qt/qtcore/configuration/_BaseConfigurableClass.html)

**Comment by kklmn** [comment]
This is a part of TaurusGUI.

Not only it is not restored on relaunch, it is gone at the next scan after auto or manual clear of the plot.

**Comment by cpascual** [comment]
> it is gone at the next scan

That means that your issue is with the scan plot, which is a special type of plot dynamically generated by **sardana's**   [DynamicPlotManager](https://github.com/sardana-org/sardana/blob/a49ed03d60d837a53bc6f04e4861adf6392a4dc3/src/sardana/taurus/qt/qtgui/macrolistener/macrolistener.py#L62).

AFAIK, we do not provide a simple way of customizing the appearance of the curves for such dynamic plots, but I agree in that it would be a nice feature. I suggest that you open a feature request [in the sardana issue tracker](https://github.com/sardana-org/sardana/issues) about it (I guess that it would make sense to implement it as part of the experimentconfiguration widget, and that it would make more sense to make it the new pyqtgraph-based plot widgets)

Alternatively, if you are ok with implementing your own custom solution it should not be too hard:
1- you should specialise the `ScanTrendSet` class (implemented in `taurus.qt.qtgui.qwt5` or in `taurus.qt.qtgui.plot` for taurus v<4.5) to use the colors/appearances you want
2- specialise a `TaurusTrend` so that it uses the class that you defined in "1" (instead of the default `ScanTrendSet`
3- add a panel to your TaurusGui with the widget that you created in "2" and use it instead of the dynamically-created plots)

Note that this solution is not general in the sense that it would be tailored to an specific set-up/scan.

I hope this helps.

**Comment by kklmn** [comment]
Thank you for explanations and suggestions!
I've put a [feature request](https://github.com/sardana-org/sardana/issues/1091)
