### ISSUE TITLE
TaurusLed : connect to a function

### ISSUE THREAD

**Issue by nfalcoz** [taurus-org/taurus#986]
Hello,

I use a TaurusLed to display if the attribute "AmpliShutterOpened" of my Tango device is true or false: 
```
etatLaserLecture = TaurusLed()
etatLaserLecture.setModel('LI/OP/OPT.02-LAS.01-ASP.01/AmpliShutterOpened')
```
I also have a button which allows to start or stop this device. Actually, i would connect my led (at every state change) to a function which could modify my button. Currently, I use : 

`etatLaserLecture.valueChangedSignal.connect(self.test)`

But my command doesn't work and the "test" function is never called.  Does anyone know the problem or another way to realize this task ?

Thanks

**Comment by cpascual** [comment]
AFAIK, the `valueChangedSignal` is only suppossed to be emitted by the taurus *write* widgets (e.g. `TaurusValueLineEdit`, `TaurusValueCheckBox`, ...), but not by the display widgets (`TaurusLabel', `TaurusLed`, ...)

In any case, personally I would attack your problem from a slightly different angle: instead of using a signal, I would simply create a widget that listens to the same attribute as your led, as in the following example, where I "taurus-ify" the button to show ON/OFF in the text depending on the value of the attribute.

The advantage of this approach is that your logic is not mixed with the view of the application (you can e.g. later on replace the led and the button does not need to change) 

```python
from taurus.qt.qtgui.application import TaurusApplication
from taurus.qt.qtgui.display import TaurusLed
from taurus.qt.qtgui.base import TaurusBaseWidget
from taurus.external.qt import Qt


class MyButton(Qt.QPushButton, TaurusBaseWidget):
    """
    A taurus-ified QPushButton that reacts on changes of an attribute
    """
    def handleEvent(self, evt_src, evt_type, evt_value):
        print(evt_value.rvalue)
        if evt_value.rvalue:
            self.setText('ON')
        else:
            self.setText('OFF')


class MyWidget(Qt.QWidget):
    def __init__(self, parent= None, model=None):
        super(MyWidget, self).__init__()
        l = Qt.QVBoxLayout()
        self.setLayout(l)

        self.led = TaurusLed()
        self.led.setModel(model)
        l.addWidget(self.led)

        self.button = MyButton()
        self.button.setModel(model)
        l.addWidget(self.button)


if __name__ == '__main__':
    import sys
    app = TaurusApplication(cmd_line_parser=None)

    w = MyWidget(model = 'eval:rand()>0.5')

    w.show()
    sys.exit(app.exec_())
```

**Comment by cpascual** [comment]
no news... closing

**Comment by marouanebj** [comment]
Hi,
I create this class for the same reason
Can you tell me what do you think of this solution ?
```python
        class IpanemaTaurusLed(TaurusLed):
            def handleEvent(self, evt_src, evt_type, evt_value):
                if evt_type in (TaurusEventType.Change, TaurusEventType.Periodic):
                    oldStatus = self.ledStatus
                    self.controller().handleEvent(evt_src, evt_type, evt_value)
                    if self.ledStatus != oldStatus:
                        self.valueChangedSignal.emit()
                else:
                    self.controller().handleEvent(evt_src, evt_type, evt_value)
```
Thanks

**Comment by cpascual** [comment]
Strictly speaking it is fine, but the same [comment](https://github.com/taurus-org/taurus/issues/986#issuecomment-516466621) applies: I personally would not use a led (which is not something that changes a value) to emit a `valueChangedSignal`.

So, Instead of doing something like:

```python
w = IpanemaTaurusLed()
w.valueChangedSignal.connect(foo)
w.setmodel('a/b/c')
```

I would create a Taurusified class that gets 'a/b/c' as its model and calls foo in its handle event. 

That way you do not make your `IpanemaLed` a critical part of the *logic* of your application
